apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-world
  namespace: develop
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        args: [ "/bin/sh", "-c", "echo Hello World > /usr/share/nginx/html/index.html"]
        ports:
        - containerPort: 80